name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm build & test
      run: |
        npm install
        npm run build
        npm test
